Add database
flykeeperB/java-filmorate pull request #5
Opened 2023-05-09 15:36 UTC by flykeeperB

Реализовано хранение в базе данных (H2), добавлены лайки, рейтинг MPA, логика дружбы между пользователями

2023-05-10 00:57 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/GenreDBStorage.java
> +        String sql = "SELECT g.* FROM film_genres AS fg LEFT JOIN " +
Почему тут используется Left Join? Бываю фильмы, в которых прописаны жанры, но таких жанров в системе нет?

2023-05-10 01:06 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        return jdbcTemplate.query(sql, this::mapRow);
Если получаются все фильмы, то для каждого фильма будет сделан запрос на его жанры. Попробуй сделать получение фильмов и его жанров в одном запросе.

2023-05-10 01:08 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +    ;
В классе встречаются такие точки с запятой. Они не нужны

2023-05-10 01:09 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +        return super.hashCode();
Если в дочернем методе вызывается базовый класс, то он не нужен, т.к. не добавляет логики

2023-05-10 01:12 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        return new ArrayList<>(Arrays.asList("*"));
Похоже тут была идея сделать так, чтобы для каждого класса вытаскивался список его полей, но в итоге кончилось все звездочкой. Но идея хорошая

2023-05-10 01:13 UTC, EvgenyKoptubenko commented
Тема дженериков пройдена на отлично. Тему исследована круто

2023-05-10 01:16 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/FilmDBStorage.java
> +    GenreDBStorage genreStorage;
Инъекции через Autowired считаются не совсем правильными, но вариант рабочий. Если есть желание, то тут отвечено почему это не совсем правильно.
https://stackoverflow.com/questions/39890849/what-exactly-is-field-injection-and-how-to-avoid-it

2023-05-10 01:17 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>      public void delete(Integer id) {
Проверь, пожалуйста, действительно ли этот запрос работает. Не нужно ли тут добавить @PathVariable?

2023-05-10 01:20 UTC, EvgenyKoptubenko commented
Если создать одного и того же пользователя несколько раз, то падает с 500-й ошибкой
curl --request POST \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 12231' \
  --data '{
	"name":"nameItem1",
	"email":"email2@2email.com",
  "login":"login",
	"birthday":"2001-01-01"
}'

{
	"timestamp": "2023-05-10T01:19:35.348+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/users"
}

Похоже нужно добавить обработчик исключений
org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Unique index or primary key violation: "PUBLIC.CONSTRAINT_INDEX_4 ON PUBLIC.USERS(LOGIN NULLS FIRST) VALUES ( /* 1 */ 'login' )"; SQL statement:
INSERT INTO users (birthday, name, login, email) VALUES (?, ?, ?, ?) [23505-214]

2023-05-10 01:21 UTC, EvgenyKoptubenko commented
Так же нужно добавить обработчик ошибок при таком запросе
curl --request PUT \
  --url http://localhost:8080/users \
  --header 'Content-Type: application/json' \
  --header 'X-Sharer-User-Id: 1' \
  --data '{
	"name":"nameItem",
	"email":"wrong_emai@lmail.com",
  "login":"login22",
	"birthday":"2012-04-23T18:25:43.511Z"
}'

Тут должен быть все-таки bad request

2023-05-10 01:21 UTC, EvgenyKoptubenko requested changes
Работа сделана хорошо. Есть предложения по улучшению кода

2023-05-10 05:36 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        return new ArrayList<>(Arrays.asList("*"));
Я решил, что было бы удобно оставить себе возможность для реализации при необходимости кастомного набора полей путем переопределения этого метода в наследниках. При написании пока везде хватало звездочки. Стоит ли отказываться? )

2023-05-10 05:38 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>      public void delete(Integer id) {
Странно, что тесты постмана прошли....

2023-05-10 21:21 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        return jdbcTemplate.query(sql, this::mapRow);
Реализовано получение фильмов и идентификаторов жанров одним запросом. Сами жанры достаются из хранилища, где, с учетом небольшого количества жанров, осуществляется их кеширование с использованием HashMap так, что в случае повторного обращения жанр не грузится, а возвращается идентификатор на уже существующий экземпляр.

2023-05-10 21:21 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +    ;
Исправлено.

2023-05-10 21:21 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +        return super.hashCode();
Исправлено.

2023-05-10 21:21 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        for (int i = 0; i < fieldNames.size(); i++) {
Исправлено.

2023-05-10 21:23 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/AbstractGenericDao.java
> +        return new ArrayList<>(Arrays.asList("*"));
Исправил. Реализовал переопределение метода получения списка полей при реализации класса FilmDBStorage c учетом того, что набор полей собирается из разных таблиц JOINом.

2023-05-10 21:24 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/storage/dataBase/FilmDBStorage.java
> +    GenreDBStorage genreStorage;
Исправил.

2023-05-10 21:24 UTC, flykeeperB commented on src/main/java/ru/yandex/practicum/filmorate/controllers/UserController.java
>      public void delete(Integer id) {
Исправил.

2023-05-11 02:17 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо.

2023-05-11 06:42 UTC, merged